---

- name: Add CI 
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm

  tasks:
    - name: Create/Update CI
      servicenow.itsm.configuration_item:
        name: Arista2
        assigned_to: admin
        environment: test
        category: Network
        asset_tag: P1000613
        serial_number: ECE-164-E10834-NO
        other:
          model_number: BL465C G7
        instance:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
      register: configuration_item

    - name: debug
      debug:
        msg: "{{ configuration_item }}"  

    
