- name: Listen to Kafka and trigger playbook
  hosts: localhost
  sources:
    - name: Listen to Kafka
      ansible.eda.kafka:
        host: "192.168.124.58"
        port: "9092"
        topic: "network-events"
        check_hostname: false
        verify_mode: CERT_OPTIONAL
  rules:
    - name: "Run playbook when interface goes down"
      condition: event.body.structured.msg is search("changed state to down")
      actions:
        run_job_template:
          name: "arista8"
          organization: "Default"
