- name: Listen to Kafka and trigger playbook
  hosts: localhost
  sources:
    - name: Listen to Kafka
      ansible.eda.kafka:
        host: "192.168.124.58"
        port: "9092"
        topic: "network-events"
        check_hostname: false
  rules:
    - name: Run playbook when interface goes down
      condition: 'event.message is search("changed state to down")'
      action:
        run_job_template:
          name: arista8
          organization: Default
