---
- name: Watch for new incidents in ServiceNow
  hosts: localhost
  sources:
    - name: Listen to ServiceNow
      cloin.eda.snow_records:
        instance: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        table: incident
        interval: 1
  vars:
    meraki_ci_sys_id: "4683f55893d6e6102a36f1d97bba1007"
    
  rules:
    - name: Trigger playbook if incident is for Meraki device
      condition: event.cmdb_ci.value == meraki_ci_sys_id
      action:
        run_playbook: 
          name: "Meraki - Switch Port"
          organization: "Default"
          post_events: true
