---
- name: Watch for new incidents in ServiceNow
  hosts: localhost
  sources:
    - name: Listen to ServiceNow
      cloin.eda.snow_records:
        instance: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        table: incident
        interval: 1
  rules:
    - name: Debug everything else
      condition: event.cmdb_ci is  defined
      action:
        debug:
          var: event.cmdb_ci.value

