---
- name: Watch for new incidents in ServiceNow
  hosts: localhost

  sources:
    - name: Listen to ServiceNow
      servicenow.itsm.records:
        instance:
          host: https://dev190278.service-now.com
          username: admin
          password: Q^ivR95Z-lhP
        table: incident
        interval: 1        

  rules:
    - name: Display full ServiceNow incident event
      condition: event is defined
      action:
        debug:
          msg: "{{ event }}"
