---
- name: Watch for new incidents in ServiceNow
  hosts: localhost

  sources:
    - name: Listen to ServiceNow
      servicenow.itsm.records:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_user }}"
          password: "{{ snow_password }}"
        table: incident
        interval: 1
        remote_servicenow_timezone: GMT
        
  rules:
    - name: Display full ServiceNow incident event
      condition: event.sys_id is defined
      action:
        print_event:
          
