---
- name: Watch for new incidents in ServiceNow
  hosts: localhost
  sources:
    - name: Listen to ServiceNow
      cloin.eda.snow_records:
        instance: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        table: incident
        interval: 1      
  rules:
    - name: Trigger playbook if incident is for Meraki device
      condition: 
        all:
          - event.cmdb_ci is defined
          - event.cmdb_ci.value == '4683f55893d6e6102a36f1d97bba1007'
      
      action:
        run_job_template: 
          name: Meraki - Switch Port
          organization: Default
          post_events: true
