---
- name: Watch for new incidents in ServiceNow
  hosts: localhost

  sources:
    - name: Listen to ServiceNow
      servicenow.itsm.records:
        instance:
          host: https://dev190278.service-now.com
          username: admin
          password: "{{ snow_password }}"
        table: incident
        interval: 1
        remote_servicenow_timezone: Australia/Melbourne
        updated_since: "2026-05-30 12:00:00"

  rules:
    - name: Display full ServiceNow incident event
      condition: event.sys_id is defined
      action:
        debug:
