- name: Listen to Kafka and trigger playbook
  hosts: localhost
  sources:
    - name: Listen to Kafka
      ansible.eda.kafka:
        host: "3.27.213.228"
        port: "9092"
        topic: "windows-logs"
        check_hostname: false
  rules:
    - name: "Identified Win Activity"
      condition: event.body.message is search("EC2AMAZ-CTJ1AR7")
      action:
        run_workflow_template:
          name: "Demo Job Template"
          organization: "Default"
          post_events: true
