---
- name: Listen to Kafka and trigger playbook
  hosts: localhost
  sources:
    - name: Listen to Kafka
      ansible.eda.kafka:
        host: "54.252.124.154"
        port: "9092"
        topic: "windows-logs"
        check_hostname: false
  rules:
    - name: "Identified Win Activity"
      condition: event.body is defined
      action:
        debug:
          var: event
#        run_job_template: 
#          name: Windows Registry
#          organization: Default
#          post_events: true
