windows- name: Listen to Kafka and trigger playbook
  hosts: localhost
  sources:
    - name: Listen to Kafka
      ansible.eda.kafka:
        host: "3.27.213.228"
        port: "9092"
        topic: "windows-logs"
        check_hostname: false
  rules:
    - name: "Identified Win Activity"
      condition: event.body.SourceName == "FluentTest"
      action:
        run_job_template: 
          name: Meraki - Switch Port
          organization: Default
          post_events: true
