---
- name: Listen to Kafka and trigger playbook
  hosts: localhost
  sources:
    - name: Listen to Kafka
      ansible.eda.kafka:
        host: "13.211.203.3"
        port: "9092"
        topic: "windows-logs"
        check_hostname: false
  rules:
    - name: "Identified Win Activity"
      condition: event.body.SourceName == "FluentTest"
      action:
        run_job_template: 
          name: Demo Job Template
          organization: Default
          post_events: true
