- name: Bring Arista interface up
  hosts: "{{ ansible_eda['event']['body']['source_ip'] | default('eos') }}"
  become: true
  gather_facts: no
  tasks:
    - name: Enable interface on Arista EOS
      arista.eos.eos_config:
        lines:
          - no shutdown
        parents: interface Ethernet1

