---
- name: Registry Update
  hosts: "all"
  gather_facts: false
  collections:
   - ansible.windows
  
  tasks:
   - name: Update Windows update by creating 
     ansible.windows.win_regedit:
      path: HKCU:\Software\TestKey
      name: TestValue
      data: True
