- name: Test Connection to Windows Server
  hosts: all
  gather_facts: false
  tasks:
    - name: Check connection with win_ping
      ansible.windows.win_ping:

    - name: Get Windows hostname
      ansible.windows.win_shell: hostname

    - name: Add User
      ansible.windows.win_user:
        name: ansible
        password: "@ns1bl3"
        state: present

    - name: DOwnload 7 zip package for installation
      win_get_url:
        url: https://www.7-zip.org/a/7z2301-x64.exe  # Update URL if needed
        dest: C:\Windows\Temp\7z_setup.exe

    - name: Install 7-Zip
      win_package:
        path: C:\Windows\Temp\7z_setup.exe
        arguments: /S  # Silent installation
        state: present

    
      
