- name: Test Connection to Windows Server
  hosts: all
  tasks:
    - name: Check connection with win_ping
      ansible.windows.win_ping:

    - name: Get Windows hostname
      ansible.windows.win_shell: hostname

    - name: Create a test file
      ansible.windows.win_file:
        path: C:\temp\ansible_test.txt
        state: touch
