- name: Test Connection to Windows Server
  hosts: all
  gather_facts: false
  tasks:
    - name: Check connection with win_ping
      ansible.windows.win_ping:

    - name: Get Windows hostname
      ansible.windows.win_shell: hostname

    - name: Add User
      ansible.windows.win_user:
        name: ansible
        password: "@ns1bl3"
        state: present

    - name: Download 7 zip package
      ansible.windows.win_get_url:
        url: https://www.7-zip.org/a/7z2409-x64.exe
        dest: C:\Users\Administrator\Downloads
        
    
      
