- name: Test Connection to Windows Server
  hosts: all
  gather_facts: false
  tasks:
    - name: Check connection with win_ping
      ansible.windows.win_ping:

    - name: Get Windows hostname
      ansible.windows.win_shell: hostname
      
